version: "3.8"

services:

  postgres:
    container_name: perusable-database
    environment:
      - POSTGRES_DB=perusable
      - POSTGRES_USER=perusable
      - POSTGRES_PASSWORD=perusable
    image: postgres:13.2
    volumes:
      - postgres:/var/lib/postgresql/data

  elasticsearch:
    container_name: perusable-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    image: elasticsearch:7.10.1
    ports:
      - 9200:9200
    volumes:
      - perusable-elasticsearch:/usr/share/elasticsearch/data

  server:
    build:
      context: ./server
    container_name: perusable-server
    depends_on:
      - postgres
      - elasticsearch
    env_file:
      - ./server/.env
    command: [ "bash", "./scripts/start.sh" ]
    ports:
      - 8000:8000
    volumes:
      - ./server:/usr/src/app

volumes:
  postgres:
  perusable-elasticsearch: