# Generated by Django 3.2.7 on 2021-10-02 02:08

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension, BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGistExtension(),
        migrations.AddField(
            model_name='wine',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='wines'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['variety', 'winery', 'description'], name='wine_text_index', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
