# Generated by Django 3.2.7 on 2021-10-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_update_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineSearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
